  CREATE TABLE "MEMBERSHIP"."MEMBERSHIP" 
   (	"MEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MEM_PW" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MEM_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MEM_BIRTH" NUMBER(6,0) NOT NULL ENABLE, 
	"MEM_NIK" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MEM_EMAIL" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"MEM_CALL" NUMBER(10,0) NOT NULL ENABLE, 
	"MEM_CELL" NUMBER(11,0) NOT NULL ENABLE, 
	"MEM_LIVE" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("MEM_ID", "MEM_PW", "MEM_NIK", "MEM_EMAIL", "MEM_CELL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;